alter table public.service_confirmations
  add column if not exists confirmation_source text
    check (confirmation_source in ('VOLUNTEER', 'COORDINATOR', 'LEADER', 'COVERAGE')),
  add column if not exists confirmed_by_user_id bigint references public.users(id) on delete set null;

create table public.coverage_requests (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedules(id) on delete cascade,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  original_volunteer_id bigint not null references public.volunteers(id),
  created_by_user_id bigint not null references public.users(id),
  winner_volunteer_id bigint references public.volunteers(id),
  status text not null default 'OPEN'
    check (status in ('OPEN', 'FILLED', 'CANCELLED', 'EXPIRED')),
  reason text not null,
  opened_early smallint not null default 0 check (opened_early in (0, 1)),
  filled_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index coverage_requests_open_assignment_unique
  on public.coverage_requests (assignment_id)
  where status = 'OPEN';
create index coverage_requests_schedule_idx on public.coverage_requests (schedule_id);
create index coverage_requests_creator_idx on public.coverage_requests (created_by_user_id);

create table public.coverage_invitations (
  id bigint generated by default as identity primary key,
  coverage_request_id bigint not null references public.coverage_requests(id) on delete cascade,
  volunteer_id bigint not null references public.volunteers(id) on delete cascade,
  invited_by_user_id bigint not null references public.users(id),
  status text not null default 'PENDING'
    check (status in ('PENDING', 'ACCEPTED', 'DECLINED', 'FILLED_BY_OTHER', 'CANCELLED', 'EXPIRED', 'NO_LONGER_ELIGIBLE')),
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  unique (coverage_request_id, volunteer_id)
);

create index coverage_invitations_volunteer_idx
  on public.coverage_invitations (volunteer_id, status, created_at);

create table public.service_contact_attempts (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  volunteer_id bigint not null references public.volunteers(id) on delete cascade,
  actor_user_id bigint not null references public.users(id),
  channel text not null check (channel in ('WHATSAPP', 'PHONE', 'EMAIL', 'IN_PERSON', 'OTHER')),
  note text,
  created_at timestamptz not null default now()
);

create index service_contact_attempts_assignment_idx
  on public.service_contact_attempts (assignment_id, created_at);

alter table public.schedule_change_events
  add column if not exists coverage_request_id bigint
    references public.coverage_requests(id) on delete set null;
create index schedule_change_events_coverage_request_idx
  on public.schedule_change_events (coverage_request_id);

alter table public.notifications
  add column if not exists coverage_request_id bigint
    references public.coverage_requests(id) on delete set null;
create index notifications_coverage_request_idx
  on public.notifications (coverage_request_id);

alter table public.coverage_requests enable row level security;
alter table public.coverage_invitations enable row level security;
alter table public.service_contact_attempts enable row level security;

revoke all on table public.coverage_requests from anon, authenticated;
revoke all on table public.coverage_invitations from anon, authenticated;
revoke all on table public.service_contact_attempts from anon, authenticated;
revoke all on sequence public.coverage_requests_id_seq from anon, authenticated;
revoke all on sequence public.coverage_invitations_id_seq from anon, authenticated;
revoke all on sequence public.service_contact_attempts_id_seq from anon, authenticated;
