-- Baseline PostgreSQL schema for the media-team scheduler.
-- Browser clients authenticate with Supabase Auth, but application data is
-- accessed through the protected API. Public tables therefore keep RLS
-- enabled without direct anon/authenticated policies.

create table public.volunteers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  max_monthly_frequency integer not null default 4 check (max_monthly_frequency > 0),
  max_consecutive_sundays integer not null default 2 check (max_consecutive_sundays > 0),
  allowed_shift text not null default 'ALL' check (allowed_shift in ('MORNING', 'NIGHT', 'ALL')),
  active smallint not null default 1 check (active in (0, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index volunteers_email_lower_unique
  on public.volunteers (lower(email))
  where email is not null;

create table public.proficiencies (
  id bigint generated by default as identity primary key,
  volunteer_id bigint not null references public.volunteers(id) on delete cascade,
  role text not null check (role in ('JIB', 'FIXED_CAM', 'SWITCHER', 'VMIX', 'COORDINATOR', 'FREEHAND')),
  level integer not null check (level between 1 and 3),
  created_at timestamptz not null default now(),
  unique (volunteer_id, role)
);

create table public.unavailabilities (
  id bigint generated by default as identity primary key,
  volunteer_id bigint not null references public.volunteers(id) on delete cascade,
  date date not null,
  shift text check (shift in ('MORNING', 'NIGHT', 'ALL') or shift is null),
  reason text,
  created_at timestamptz not null default now(),
  unique (volunteer_id, date, shift)
);

create index unavailabilities_date_idx on public.unavailabilities (date);

create table public.schedules (
  id bigint generated by default as identity primary key,
  year integer not null,
  month integer not null check (month between 1 and 12),
  status text not null default 'DRAFT' check (status in ('DRAFT', 'PUBLISHED')),
  locked_slots text not null default '[]',
  warnings text not null default '[]',
  published_version integer not null default 0 check (published_version >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (year, month)
);

create table public.assignments (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedules(id) on delete cascade,
  volunteer_id bigint not null references public.volunteers(id) on delete cascade,
  date date not null,
  shift text not null check (shift in ('MORNING', 'NIGHT')),
  role text not null check (role in ('JIB', 'FIXED_CAM', 'SWITCHER', 'VMIX', 'COORDINATOR', 'FREEHAND')),
  is_trainee smallint not null default 0 check (is_trainee in (0, 1)),
  created_at timestamptz not null default now(),
  unique (date, shift, role, is_trainee)
);

create index assignments_schedule_id_idx on public.assignments (schedule_id);
create index assignments_volunteer_date_idx on public.assignments (volunteer_id, date);

create table public.schedule_versions (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedules(id) on delete cascade,
  version integer not null check (version > 0),
  assignments text not null,
  warnings text not null default '[]',
  published_at timestamptz not null default now(),
  unique (schedule_id, version)
);

create table public.users (
  id bigint generated by default as identity primary key,
  volunteer_id bigint unique references public.volunteers(id) on delete set null,
  auth_user_id uuid unique,
  name text not null,
  email text not null,
  role text not null check (role in ('LEADER', 'VOLUNTEER')),
  approval_status text not null default 'APPROVED' check (approval_status in ('PENDING', 'APPROVED')),
  email_confirmed_at timestamptz,
  active smallint not null default 1 check (active in (0, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index users_email_lower_unique on public.users (lower(email));
create index users_pending_approval_idx
  on public.users (approval_status, email_confirmed_at, created_at);

create table public.service_confirmations (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedules(id) on delete cascade,
  assignment_id bigint references public.assignments(id) on delete set null,
  volunteer_id bigint not null references public.volunteers(id) on delete cascade,
  status text not null default 'AWAITING' check (status in ('AWAITING', 'CONFIRMED', 'EXCHANGE_PENDING', 'SUPERSEDED')),
  last_reminder_on date,
  reminder_count integer not null default 0 check (reminder_count >= 0),
  provider_message_id text,
  last_error text,
  responded_at timestamptz,
  superseded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (assignment_id, volunteer_id)
);

create index service_confirmations_due_idx
  on public.service_confirmations (status, last_reminder_on, assignment_id);
create index service_confirmations_schedule_volunteer_idx
  on public.service_confirmations (schedule_id, volunteer_id);
create index service_confirmations_volunteer_id_idx
  on public.service_confirmations (volunteer_id);

create table public.schedule_exchanges (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedules(id) on delete cascade,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  target_assignment_id bigint references public.assignments(id) on delete cascade,
  requester_id bigint not null references public.volunteers(id) on delete cascade,
  target_volunteer_id bigint not null references public.volunteers(id) on delete cascade,
  status text not null default 'PENDING' check (status in ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'EXPIRED')),
  reason text,
  rejection_reason text,
  confirmation_id bigint references public.service_confirmations(id) on delete set null,
  last_reminder_on date,
  last_error text,
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  completed_at timestamptz,
  check (requester_id <> target_volunteer_id)
);

create index schedule_exchanges_schedule_id_idx on public.schedule_exchanges (schedule_id);
create index schedule_exchanges_requester_id_idx on public.schedule_exchanges (requester_id);
create index schedule_exchanges_target_volunteer_id_idx on public.schedule_exchanges (target_volunteer_id);
create index schedule_exchanges_status_idx on public.schedule_exchanges (status);
create index schedule_exchanges_confirmation_id_idx on public.schedule_exchanges (confirmation_id);
create unique index schedule_exchanges_pending_assignment_unique
  on public.schedule_exchanges (assignment_id)
  where status = 'PENDING';
create unique index schedule_exchanges_pending_target_unique
  on public.schedule_exchanges (target_assignment_id)
  where status = 'PENDING' and target_assignment_id is not null;

create table public.schedule_change_events (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedules(id) on delete cascade,
  from_version integer not null check (from_version >= 0),
  to_version integer not null check (to_version > from_version),
  exchange_id bigint references public.schedule_exchanges(id) on delete set null,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  previous_volunteer_id bigint not null references public.volunteers(id),
  new_volunteer_id bigint not null references public.volunteers(id),
  changed_by_user_id bigint not null references public.users(id),
  created_at timestamptz not null default now()
);

create index schedule_change_events_schedule_id_idx on public.schedule_change_events (schedule_id);
create index schedule_change_events_exchange_id_idx on public.schedule_change_events (exchange_id);
create index schedule_change_events_assignment_id_idx on public.schedule_change_events (assignment_id);
create index schedule_change_events_previous_volunteer_id_idx on public.schedule_change_events (previous_volunteer_id);
create index schedule_change_events_new_volunteer_id_idx on public.schedule_change_events (new_volunteer_id);
create index schedule_change_events_changed_by_user_id_idx on public.schedule_change_events (changed_by_user_id);

create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  type text not null,
  exchange_id bigint references public.schedule_exchanges(id) on delete set null,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index notifications_user_created_at_idx on public.notifications (user_id, created_at desc);
create index notifications_exchange_id_idx on public.notifications (exchange_id);

alter table public.volunteers enable row level security;
alter table public.proficiencies enable row level security;
alter table public.unavailabilities enable row level security;
alter table public.schedules enable row level security;
alter table public.assignments enable row level security;
alter table public.schedule_versions enable row level security;
alter table public.users enable row level security;
alter table public.service_confirmations enable row level security;
alter table public.schedule_exchanges enable row level security;
alter table public.schedule_change_events enable row level security;
alter table public.notifications enable row level security;

revoke all privileges on all tables in schema public from anon, authenticated;
revoke all privileges on all sequences in schema public from anon, authenticated;
